modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/nadia8666/utm/issues/"

[[mods]]
modId="utm"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/nadia8666/utm/"
logoFile="utm_icon.png"
credits='''
the people behin tcreate
the ones who made create aeronautics & sable
all of the jijed mods
bry - grimble mod (a wonderful contribution)
sophisticated backpacks guy & backported spears guy - makign a very difficult to expand mod
figura team - adding many mod incompatabilties i have had to mixin to fix
neoforge - making a great modloader
minecraft - making a bad game goodish
punchy developer - for making a closed source all rights reserved mod that i had to mixn to add figura compat. for
'''
authors="nadiarr, rblxpikmin"
description='''
all the small things.

utility & compat mod between various mods (see deps.)
automatically updates from github, disablable in config (though, if working with servers I wouldn't recommend it.
'''

[modproperties.utm]
gitHash="${git_hash}"

[[mixins]]
config="utm.mixins.json"

[[dependencies.utm]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.218,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.utm]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


#[features.utm]
#openGLVersion="[3.2,)"

# CREATE
[[dependencies.utm]]
modId="create"
type="required"
versionRange="[6.0.9,6.1.0)"
ordering="AFTER"
side="BOTH"

# EMI
[[dependencies.utm]]
modId="emi"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"

[[dependencies.utm]]
modId="jei"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"


# SOPHISTICATED BACKPACKS
[[dependencies.utm]]
modId="sophisticatedbackpacks"
type="optional"
versionRange=","
ordering="AFTER"
side="BOTH"

# SPEARS
[[dependencies.utm]]
modId="spears"
type="optional"
versionRange=","
ordering="AFTER"
side="BOTH"

# SHOWCASE ITEM
[[dependencies.utm]]
modId="showcaseitem"
type="required"
versionRange=","
ordering="AFTER"
side="BOTH"

# FIGURA
[[dependencies.utm]]
modId="figura"
type="optional"
versionRange=","
ordering="AFTER"
side="CLIENT"

# GRAVESTONES
[[dependencies.utm]]
modId="gravestone"
type="optional"
versionRange=","
ordering="AFTER"
side="BOTH"

# EXTREME SOUND MUFFLER
[[dependencies.utm]]
modId="extremesoundmuffler"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"

# GRIMBLE MOD
[[dependencies.utm]]
modId="grimble_mod"
type="required"
versionRange=","
ordering="AFTER"
side="BOTH"

# SABLE
[[dependencies.utm]]
modId="sable"
type="required"
versionRange=","
ordering="AFTER"
side="BOTH"

# CREATE AERONAUTICS
[[dependencies.utm]]
modId="aeronautics"
type="required"
versionRange=","
ordering="AFTER"
side="BOTH"

# PUNCHY
[[dependencies.utm]]
modId="punchy"
type="optional"
versionRange=","
ordering="AFTER"
side="CLIENT"